mutation JugadorInsert(
  $nombre: String!
  $numeroCamiseta: Int!
  $posicion: String!
  $fechaNacimiento: Date!
  $equipoId: UUID!
) @auth(level: PUBLIC) {
  jugador_insert(
    data: {
      nombre: $nombre
      numeroCamiseta: $numeroCamiseta
      posicion: $posicion
      fechaNacimiento: $fechaNacimiento
      equipoId: $equipoId
    }
  )
}