extend type Arbitro {
  """
  ✨ Implicit foreign key field based on `Arbitro`.`deporte`. It must match the value of `Deporte`.`id`. See `@ref` for how to customize it.
  """
  deporteId: UUID! @fdc_generated(from: "Arbitro.deporte", purpose: IMPLICIT_REF_FIELD)
}
extend type Division {
  """
  ✨ Implicit foreign key field based on `Division`.`deporte`. It must match the value of `Deporte`.`id`. See `@ref` for how to customize it.
  """
  deporteId: UUID! @fdc_generated(from: "Division.deporte", purpose: IMPLICIT_REF_FIELD)
}
extend type Equipo {
  """
  ✨ Implicit foreign key field based on `Equipo`.`division`. It must match the value of `Division`.`id`. See `@ref` for how to customize it.
  """
  divisionId: UUID! @fdc_generated(from: "Equipo.division", purpose: IMPLICIT_REF_FIELD)
}
extend type Jugador {
  """
  ✨ Implicit foreign key field based on `Jugador`.`equipo`. It must match the value of `Equipo`.`id`. See `@ref` for how to customize it.
  """
  equipoId: UUID! @fdc_generated(from: "Jugador.equipo", purpose: IMPLICIT_REF_FIELD)
}
extend type JugadorFavorito {
  """
  ✨ Implicit foreign key field based on `JugadorFavorito`.`jugador`. It must match the value of `Jugador`.`id`. See `@ref` for how to customize it.
  """
  jugadorId: UUID! @fdc_generated(from: "JugadorFavorito.jugador", purpose: IMPLICIT_REF_FIELD)
  """
  ✨ Implicit foreign key field based on `JugadorFavorito`.`usuario`. It must match the value of `Usuario`.`id`. See `@ref` for how to customize it.
  """
  usuarioId: String! @fdc_generated(from: "JugadorFavorito.usuario", purpose: IMPLICIT_REF_FIELD)
}
extend type LogAccion {
  """
  ✨ Implicit foreign key field based on `LogAccion`.`usuario`. It must match the value of `Usuario`.`id`. See `@ref` for how to customize it.
  """
  usuarioId: String! @fdc_generated(from: "LogAccion.usuario", purpose: IMPLICIT_REF_FIELD)
}
extend type Partido {
  """
  ✨ Implicit foreign key field based on `Partido`.`arbitro`. It must match the value of `Arbitro`.`id`. See `@ref` for how to customize it.
  """
  arbitroId: UUID! @fdc_generated(from: "Partido.arbitro", purpose: IMPLICIT_REF_FIELD)
  """
  ✨ Implicit foreign key field based on `Partido`.`division`. It must match the value of `Division`.`id`. See `@ref` for how to customize it.
  """
  divisionId: UUID! @fdc_generated(from: "Partido.division", purpose: IMPLICIT_REF_FIELD)
  """
  ✨ Implicit foreign key field based on `Partido`.`equipoLocal`. It must match the value of `Equipo`.`id`. See `@ref` for how to customize it.
  """
  equipoLocalId: UUID! @fdc_generated(from: "Partido.equipoLocal", purpose: IMPLICIT_REF_FIELD)
  """
  ✨ Implicit foreign key field based on `Partido`.`equipoVisitante`. It must match the value of `Equipo`.`id`. See `@ref` for how to customize it.
  """
  equipoVisitanteId: UUID! @fdc_generated(from: "Partido.equipoVisitante", purpose: IMPLICIT_REF_FIELD)
}
extend type Reglamento {
  """
  ✨ Implicit foreign key field based on `Reglamento`.`deporte`. It must match the value of `Deporte`.`id`. See `@ref` for how to customize it.
  """
  deporteId: UUID! @fdc_generated(from: "Reglamento.deporte", purpose: IMPLICIT_REF_FIELD)
}
extend type SponsorUbicacion {
  """
  ✨ Implicit foreign key field based on `SponsorUbicacion`.`sponsor`. It must match the value of `Sponsor`.`id`. See `@ref` for how to customize it.
  """
  sponsorId: UUID! @fdc_generated(from: "SponsorUbicacion.sponsor", purpose: IMPLICIT_REF_FIELD)
}
