extend type Query {
  """
  ✨ Look up a single `Arbitro` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  arbitro(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Arbitro_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Arbitro_FirstRow
  ): Arbitro @fdc_generated(from: "Arbitro", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `Deporte` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  deporte(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Deporte_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Deporte_FirstRow
  ): Deporte @fdc_generated(from: "Deporte", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `Division` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  division(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Division_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Division_FirstRow
  ): Division @fdc_generated(from: "Division", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `Equipo` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  equipo(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Equipo_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Equipo_FirstRow
  ): Equipo @fdc_generated(from: "Equipo", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `Jugador` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  jugador(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Jugador_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Jugador_FirstRow
  ): Jugador @fdc_generated(from: "Jugador", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `JugadorFavorito` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  jugadorFavorito(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: JugadorFavorito_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: JugadorFavorito_FirstRow
  ): JugadorFavorito @fdc_generated(from: "JugadorFavorito", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `LogAccion` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  logAccion(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: LogAccion_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: LogAccion_FirstRow
  ): LogAccion @fdc_generated(from: "LogAccion", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `Partido` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  partido(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Partido_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Partido_FirstRow
  ): Partido @fdc_generated(from: "Partido", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `Reglamento` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  reglamento(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Reglamento_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Reglamento_FirstRow
  ): Reglamento @fdc_generated(from: "Reglamento", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `Sponsor` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  sponsor(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Sponsor_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Sponsor_FirstRow
  ): Sponsor @fdc_generated(from: "Sponsor", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `SponsorUbicacion` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  sponsorUbicacion(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: SponsorUbicacion_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: SponsorUbicacion_FirstRow
  ): SponsorUbicacion @fdc_generated(from: "SponsorUbicacion", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `Usuario` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  usuario(
    """
    The unique ID of the object.
    """
    id: String

    """
    ✨ `_expr` server value variant of `id` (The unique ID of the object.)
    """
    id_expr: String_Expr

    """
    The key used to identify the object.
    """
    key: Usuario_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Usuario_FirstRow
  ): Usuario @fdc_generated(from: "Usuario", purpose: QUERY_SINGLE)
  """
  ✨ List `Arbitro` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  arbitros(
    """
    Filter condition to narrow down the query results.
    """
    where: Arbitro_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Arbitro_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Arbitro_Having
  ): [Arbitro!]! @fdc_generated(from: "Arbitro", purpose: QUERY_MULTIPLE)
  """
  ✨ List `Deporte` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  deportes(
    """
    Filter condition to narrow down the query results.
    """
    where: Deporte_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Deporte_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Deporte_Having
  ): [Deporte!]! @fdc_generated(from: "Deporte", purpose: QUERY_MULTIPLE)
  """
  ✨ List `Division` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  divisions(
    """
    Filter condition to narrow down the query results.
    """
    where: Division_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Division_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Division_Having
  ): [Division!]! @fdc_generated(from: "Division", purpose: QUERY_MULTIPLE)
  """
  ✨ List `Equipo` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  equipos(
    """
    Filter condition to narrow down the query results.
    """
    where: Equipo_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Equipo_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Equipo_Having
  ): [Equipo!]! @fdc_generated(from: "Equipo", purpose: QUERY_MULTIPLE)
  """
  ✨ List `Jugador` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  jugadors(
    """
    Filter condition to narrow down the query results.
    """
    where: Jugador_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Jugador_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Jugador_Having
  ): [Jugador!]! @fdc_generated(from: "Jugador", purpose: QUERY_MULTIPLE)
  """
  ✨ List `JugadorFavorito` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  jugadorFavoritos(
    """
    Filter condition to narrow down the query results.
    """
    where: JugadorFavorito_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [JugadorFavorito_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: JugadorFavorito_Having
  ): [JugadorFavorito!]! @fdc_generated(from: "JugadorFavorito", purpose: QUERY_MULTIPLE)
  """
  ✨ List `LogAccion` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  logAccions(
    """
    Filter condition to narrow down the query results.
    """
    where: LogAccion_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [LogAccion_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: LogAccion_Having
  ): [LogAccion!]! @fdc_generated(from: "LogAccion", purpose: QUERY_MULTIPLE)
  """
  ✨ List `Partido` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  partidos(
    """
    Filter condition to narrow down the query results.
    """
    where: Partido_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Partido_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Partido_Having
  ): [Partido!]! @fdc_generated(from: "Partido", purpose: QUERY_MULTIPLE)
  """
  ✨ List `Reglamento` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  reglamentos(
    """
    Filter condition to narrow down the query results.
    """
    where: Reglamento_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Reglamento_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Reglamento_Having
  ): [Reglamento!]! @fdc_generated(from: "Reglamento", purpose: QUERY_MULTIPLE)
  """
  ✨ List `Sponsor` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  sponsors(
    """
    Filter condition to narrow down the query results.
    """
    where: Sponsor_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Sponsor_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Sponsor_Having
  ): [Sponsor!]! @fdc_generated(from: "Sponsor", purpose: QUERY_MULTIPLE)
  """
  ✨ List `SponsorUbicacion` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  sponsorUbicacions(
    """
    Filter condition to narrow down the query results.
    """
    where: SponsorUbicacion_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [SponsorUbicacion_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: SponsorUbicacion_Having
  ): [SponsorUbicacion!]! @fdc_generated(from: "SponsorUbicacion", purpose: QUERY_MULTIPLE)
  """
  ✨ List `Usuario` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  usuarios(
    """
    Filter condition to narrow down the query results.
    """
    where: Usuario_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Usuario_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Usuario_Having
  ): [Usuario!]! @fdc_generated(from: "Usuario", purpose: QUERY_MULTIPLE)
}
