type Usuario @table {
  id: UUID! @default(expr: "uuidV4()")

  nombre: String!
  email: String! @unique

  tipoUsuario: String! @default(value: "usuario")
  estado: Boolean! @default(value: true)

  fechaRegistro: Timestamp! @default(expr: "request.time")
}

type Deporte @table {
  id: UUID! @default(expr: "uuidV4()")

  nombre: String! @unique
  descripcion: String

  fechaCreacion: Timestamp! @default(expr: "request.time")
}

type Division @table {
  id: UUID! @default(expr: "uuidV4()")

  nombre: String!
  descripcion: String
  nivel: String!

  deporte: Deporte!
}

type Equipo @table {
  id: UUID! @default(expr: "uuidV4()")

  nombre: String!
  ciudad: String

  logoUrl: String
  fechaFundacion: Date

  division: Division!
}

type Jugador @table {
  id: UUID! @default(expr: "uuidV4()")

  nombre: String!
  numeroCamiseta: Int
  posicion: String

  fechaNacimiento: Date
  fotoUrl: String

  equipo: Equipo!
}

type Arbitro @table {
  id: UUID! @default(expr: "uuidV4()")

  nombre: String!
  email: String
  telefono: String

  experienciaAnios: Int

  deporte: Deporte!
}

type Partido @table {
  id: UUID! @default(expr: "uuidV4()")

  division: Division!
  arbitro: Arbitro!

  equipoLocal: Equipo!
  equipoVisitante: Equipo!

  fechaPartido: Date!
  horaPartido: String!

  estado: String!

  resultadoLocal: Int
  resultadoVisitante: Int

  ubicacion: String
}

type JugadorFavorito @table {
  id: UUID! @default(expr: "uuidV4()")

  usuario: Usuario!
  jugador: Jugador!

  fechaVoto: Timestamp! @default(expr: "request.time")
}

type Sponsor @table {
  id: UUID! @default(expr: "uuidV4()")

  nombre: String!
  email: String
  telefono: String

  logoUrl: String!

  slogan: String
  descripcionBreve: String

  sitioWeb: String
  fechaContrato: Date

  estado: Boolean! @default(value: true)
}

type SponsorUbicacion @table {
  id: UUID! @default(expr: "uuidV4()")

  sponsor: Sponsor!

  ubicacion: String!
  tipoUbicacion: String!
}

type Reglamento @table {
  id: UUID! @default(expr: "uuidV4()")

  titulo: String!
  contenido: String!
  orden: Int!

  fechaCreacion: Timestamp! @default(expr: "request.time")

  deporte: Deporte!
}

type LogAccion @table {
  id: UUID! @default(expr: "uuidV4()")

  usuario: Usuario!

  tipoAccion: String!
  tablaAfectada: String
  idRegistroAfectado: String
  descripcion: String

  fechaAccion: Timestamp! @default(expr: "request.time")
}
type ProductoCantina @table {
  id: UUID! @default(expr: "uuidV4()")
  nombre: String!
  descripcion: String
  precio: Float!
  categoria: String
  disponible: Boolean! @default(value: true)
  imagenUrl: String
  fechaCreacion: Timestamp! @default(expr: "request.time")
}

